<?php

use Drupal\node\NodeInterface;

/**
 * Implements hook_mail().
 */
function email_form_mail($key, &$message, $params) {
  switch ($key) {
    case 'node_edition':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('A node has been modified.');
      $message['body'][] = check_markup($params['message']);
      break;
  }
}

/**
 * Implements hook_node_update().
 */
function email_form_node_update(NodeInterface $node) {
  $database = \Drupal::database();
  $mailManager = \Drupal::service('plugin.manager.mail');

  $emails = $database->select('email_form', 'ef')
    ->fields('ef', array('email'))
    ->condition('nid', $node->id())
    ->execute();

  foreach ($emails as $record) {
    $module = 'email_form';
    $key = 'node_edition';
    $to = $record->email;
    $params['message'] = t('@node has been edited.', array('@node' => $node->getTitle()));
    $langcode = \Drupal::currentUser()->getPreferredLangcode();
    $send = true;

    $mailManager->mail($module, $key, $to, $langcode, $params, NULL, $send);
  }
}