<?php



function annonce_theme($existing, $type, $theme, $path) {
  return array(
              'annonce' => array(
                'file' => 'annonce.page.inc',
                'render element' => 'elements',
                ),
              );
}

/**
 *
 * @param array $variables
 * @return array $suggestion
 */
function annonce_theme_suggestions_annonce(array $variables) {
  $suggestions[] = 'annonce__' . $variables['elements']['#view_mode'];

  return suggestions;
}
