<?php

/**
 * @file
 * Contains like.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function like_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the like module.
    case 'help.page.like':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Button Like available for liking') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_node_update().
 */
function like_node_update(NodeInterface $node) {
  /*$database = \Drupal::database();

  $nb = $database->select('nb', 'nb')
    ->fields('nb', array('nb'))
    ->condition('nid', $node->id())
    ->execute();*/
}
