# Static routes
config_src.diff:
  path: '/admin/config/development/configuration/config-src/{config_source}/diff/{source_name}/{target_name}'
  defaults:
    _controller: '\Drupal\config_src\Controller\DiffController::diff'
    target_name: NULL
  requirements:
    _permission: 'synchronize configuration'

config_src.diff_collection:
  path: '/admin/config/development/configuration/config-src/{config_source}/diff_collection/{collection}/{source_name}/{target_name}'
  defaults:
    _controller: '\Drupal\config_src\Controller\DiffController::diff'
    target_name: NULL
  requirements:
    _permission: 'synchronize configuration'

config_src.single_import:
  path: '/admin/config/development/configuration/config-src/single-import/{config_source}/{config_name}'
  defaults:
    _controller: '\Drupal\config_src\Controller\ImportController::configImport'
    target_name: NULL
  requirements:
    _permission: 'synchronize configuration'

config_src.single_import_collection:
  path: '/admin/config/development/configuration/config-src/single-import-collection/{config_source}/{collection}/{config_name}'
  defaults:
    _controller: '\Drupal\config_src\Controller\ImportController::configCollectionImport'
    target_name: NULL
  requirements:
    _permission: 'synchronize configuration'
